import { createClient } from 'npm:@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });

  try {
    const authHeader = req.headers.get('Authorization');
    if (!authHeader?.startsWith('Bearer ')) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    const url = Deno.env.get('SUPABASE_URL')!;
    const anon = Deno.env.get('SUPABASE_ANON_KEY')!;
    const service = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

    // Identify caller
    const userClient = createClient(url, anon, { global: { headers: { Authorization: authHeader } } });
    const token = authHeader.replace('Bearer ', '');
    const { data: claims, error: claimsErr } = await userClient.auth.getClaims(token);
    if (claimsErr || !claims?.claims?.sub) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), {
        status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }
    const callerId = claims.claims.sub as string;

    // Verify admin
    const admin = createClient(url, service);
    const { data: userData } = await admin.auth.admin.getUserById(callerId);
    const callerEmail = userData?.user?.email;
    const isSuperAdminEmail = callerEmail === 'ebenezeraledu@gmail.com';
    const { data: isAdmin, error: roleErr } = await admin.rpc('has_role', { _user_id: callerId, _role: 'admin' });
    if (!isSuperAdminEmail && (roleErr || !isAdmin)) {
      return new Response(JSON.stringify({ error: 'Forbidden' }), {
        status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      });
    }

    // Fetch data
    const [{ data: users }, { data: calendars }, { data: postLog }, { data: linkedinConns }] = await Promise.all([
      admin.auth.admin.listUsers({ page: 1, perPage: 1000 }),
      admin.from('calendars').select('id, user_id, niche, posts, created_at, frozen'),
      admin.from('linkedin_post_log').select('user_id, calendar_id, status, posted_at'),
      admin.from('linkedin_connections').select('user_id, linkedin_name, created_at'),
    ]);

    const usersList = (users as any)?.users || [];
    const cals = calendars || [];
    const logs = postLog || [];
    const conns = linkedinConns || [];

    // Aggregate per user
    type Row = {
      user_id: string;
      email: string;
      created_at: string;
      linkedin_connected: boolean;
      calendars: number;
      total_posts: number;
      generated_posts: number;
      manual_posts: number;
      edited_posts: number;
      posted_success: number;
      posted_failed: number;
      success_rate: number;
    };

    const rows = new Map<string, Row>();
    for (const u of usersList) {
      rows.set(u.id, {
        user_id: u.id,
        email: u.email || '(no email)',
        created_at: u.created_at,
        linkedin_connected: false,
        calendars: 0,
        total_posts: 0,
        generated_posts: 0,
        manual_posts: 0,
        edited_posts: 0,
        posted_success: 0,
        posted_failed: 0,
        success_rate: 0,
      });
    }

    for (const conn of conns) {
      const r = rows.get(conn.user_id);
      if (r) r.linkedin_connected = true;
    }

    for (const cal of cals) {
      const r = rows.get(cal.user_id);
      if (!r) continue;
      r.calendars += 1;
      const posts = Array.isArray(cal.posts) ? cal.posts : [];
      r.total_posts += posts.length;
      for (const p of posts) {
        // A post is "manual" if it was created manually or the AI draft was edited.
        // Default (no marker) posts were generated by the initial calendar generation.
        const source = (p as any)?.source;
        const edited = !!(p as any)?.edited;
        if (source === 'manual') r.manual_posts += 1;
        else r.generated_posts += 1;
        if (edited) r.edited_posts += 1;
      }
    }

    for (const log of logs) {
      const r = rows.get(log.user_id);
      if (!r) continue;
      if (log.status === 'success') r.posted_success += 1;
      else if (log.status === 'failed' || log.status === 'error') r.posted_failed += 1;
    }

    const perUser = Array.from(rows.values()).map((r) => {
      const attempts = r.posted_success + r.posted_failed;
      r.success_rate = attempts > 0 ? Math.round((r.posted_success / attempts) * 100) : 0;
      return r;
    }).sort((a, b) => b.total_posts - a.total_posts);

    // Overall totals
    const totals = perUser.reduce((acc, r) => {
      acc.calendars += r.calendars;
      acc.total_posts += r.total_posts;
      acc.generated_posts += r.generated_posts;
      acc.manual_posts += r.manual_posts;
      acc.edited_posts += r.edited_posts;
      acc.posted_success += r.posted_success;
      acc.posted_failed += r.posted_failed;
      if (r.linkedin_connected) acc.linkedin_connected += 1;
      return acc;
    }, { calendars: 0, total_posts: 0, generated_posts: 0, manual_posts: 0, edited_posts: 0, posted_success: 0, posted_failed: 0, linkedin_connected: 0 });

    const attemptsTotal = totals.posted_success + totals.posted_failed;
    const overallSuccessRate = attemptsTotal > 0 ? Math.round((totals.posted_success / attemptsTotal) * 100) : 0;

    return new Response(JSON.stringify({
      summary: {
        total_users: usersList.length,
        active_users_7d: usersList.filter((u: any) => u.last_sign_in_at && (Date.now() - new Date(u.last_sign_in_at).getTime() < 7 * 86400000)).length,
        linkedin_connected: totals.linkedin_connected,
        total_calendars: totals.calendars,
        total_posts: totals.total_posts,
        generated_posts: totals.generated_posts,
        manual_posts: totals.manual_posts,
        edited_posts: totals.edited_posts,
        posted_success: totals.posted_success,
        posted_failed: totals.posted_failed,
        overall_success_rate: overallSuccessRate,
      },
      users: perUser,
    }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
  } catch (e: any) {
    return new Response(JSON.stringify({ error: e.message || 'Server error' }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
